#!/bin/bash

set -uo pipefail

# Configure system locale to en_US.UTF-8
sed -i 's/#\(en_US.UTF-8 UTF-8\)/\1/g' /etc/locale.gen
locale-gen
echo 'LANG=en_US.UTF-8' > /etc/locale.conf

# Add archsink repo
cat <<EOF >> /etc/pacman.conf

[archsink]
Server = https://github.com/archsink/\$arch/releases/latest/download
SigLevel = Never

[ppr]
Server = https://raw.githubusercontent.com/parchlinux-arm/ppr/main/aarch64/
SigLevel = Never

EOF

# Enable parallel downloads
sed -i 's/#\(ParallelDownloads \)/\1/g' /etc/pacman.conf

# Install useful packages
packages=(
  volumeicon
  network-manager-applet
  parch-dwm-dots
  thunar
  picom
  feh
  parch-wallpapers
  nitrogen
  flameshot
  dunst
  lxqt-policykit
  arc-gtk-theme
  papirus-icon-theme
  sddm
  parch-branding
  noto-fonts
  vazirmatn-fonts
  ttf-dejavu
  parch-emoji-ios
  arch-install-scripts
  avahi
  curl
  git
  htop
  btop
  iwd
  man-db
  neovim
  pacman-contrib
  yay-bin
  python
  rsync
  sudo
  tmux
  tree
  neofetch-git
  zsh
  vim
)
pacman -Syu --noconfirm --needed "${packages[@]}"

#dwm dot files

cd /tmp
git clone https://github.com/parchlinux/dwm-dots.git
cd dwm-dots
cd etc/skel
mv config /home/alarm/.config
mv dwm /home/alarm/.dwm
chmod 777 /home/alarm/.config
chmod 777 /home/alarm/.dwm
chmod +x /home/alarm/.dwm/autostart.sh

rm -rf /tmp/dwm-dots

# Enable services
systemctl enable avahi-daemon iwd
systemctl enable sddm


# Prepare system for containers (e.g. for use with K3s)
# https://github.com/k3s-io/k3s/issues/2067#issuecomment-664048424
#if ! grep -q cgroup /boot/cmdline.txt; then
#  sed -i '$ s/$/ cgroup_memory=1 cgroup_enable=memory/g' /boot/cmdline.txt
#fi
