# Adapted from https://github.com/andrewboring/alarm-images/blob/master/.github/workflows/build.yml

name: Build Images

on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows: ['Trigger Build']
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ['aarch64', 'rpi-armv7', 'rpi-aarch64']
        flavor: ['vanilla']
        include:
        - arch: rpi-aarch64
          flavor: pi4

    steps:
    - uses: actions/checkout@v3
    - name: Configure Git user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y parted wget dosfstools zip arch-install-scripts
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm,arm64
    - name: Build image
      run: |
        script=""
        for script_name in "${{ matrix.arch }}-${{ matrix.flavor }}" "${{ matrix.flavor }}"; do
          script_path="setup/$script_name"
          if [ -f "$script_path" ]; then
            script="$script_path"
            break
          fi
        done
        sudo ./create-image 4G ${{ matrix.arch }} $script
    - name: Rename image
      id: rename-image
      run: |
        image_in_name="archlinux-${{ matrix.arch }}.img"
        image_out_name="archlinux-${{ matrix.arch }}-${{ matrix.flavor }}-$(date '+%Y-%m-%d').img"
        mv "$image_in_name" "$image_out_name"
        echo "image_name=$image_out_name" >> "$GITHUB_OUTPUT"
    - name: Compress image
      run: zip -v "${{ steps.rename-image.outputs.image_name }}"{.zip,}
    - name: Upload image
      uses: actions/upload-artifact@v3
      with:
        name: "${{ steps.rename-image.outputs.image_name }}.zip"
        path: "${{ steps.rename-image.outputs.image_name }}.zip"
    - name: Create tag
      if: github.ref == 'refs/heads/main'
      id: create-tag
      run: |
        snapshot="$(date -I)"
        tag="$snapshot"
        echo "snapshot=$snapshot" >> "$GITHUB_OUTPUT"
        echo "tag=$tag" >> "$GITHUB_OUTPUT"
        git fetch --tags
        if git rev-parse "$tag" >/dev/null 2>&1; then
          echo "tag_created=false" >> "$GITHUB_OUTPUT"
        else
          git tag -am "$snapshot" "$tag"
          git push origin "$tag"
          echo "tag_created=true" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
    - name: Create GitHub release
      if: ${{ steps.create-tag.outputs.tag_created == 'true' }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.create-tag.outputs.tag }}
        name: ${{ steps.create-tag.outputs.snapshot }}
        files: "${{ steps.rename-image.outputs.image_name }}.zip"
